### ISSUE TITLE
[FR] Support Multiple Redshift Connections

### ISSUE THREAD

**Issue by russellpierce** [kristiewirth/datto#1]
### Description of Requested Feature

Right now the database object can only use a single set of env vars for connection credentials.  But, we have a production and a development redshift cluster - depending on what we're working on we may want to query one or the other, perhaps even within the same notebook.

### Context

Once we have this feature I will be able to deprecate an internal package and guide folks to use `datto` instead!  The big win for me is that I will be able to execute heavy queries against dev, save the results to S3, expose them as an external table, and then have them available to prod!

### Priority

Medium Low.  I'm thinking by Q4 2020 or Q1 2021 will be totally fine. I see more python people starting up who could use a smoother onramp for querying Redshift from Python.  

### Resources

None

**Comment by kristiewirth** [comment]
@russellpierce Is this something that is still a priority?

**Comment by russellpierce** [comment]
Yeah. Doesn't have to be in datto per se. But a standard way of connecting is still something I'm looking for. A lot of copy/paste ATM.

**Comment by kristiewirth** [comment]
Closing since `featurestore` is the new best internal practice for SQL connections and any updates should be made there. Example code to connect:

```
fs = FeatureStore(
   host=os.environ.get("SQLHOST"),
   port=os.environ.get("SQLPORT"),
   user=os.environ.get("SQLUSER"),
   password=os.environ.get("SQLPASSWORD")
)
df = fs.load_features('weekly_activity')
```
