### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KjelleJ** [kristiewirth/datto#2]
### Description
model_testing => CatBoostError: You can't change params of fitted model
### Steps to Reproduce
Run 'tm.model_testing(X_train, y_train, pipeline, "classification", "precision", save_to_csv=False)' in datto_exampels.ipynb (or Golden_path_to_ml)

### Theories or Anti-Theories
Using Anaconda3. Version problems?

**Comment by kristiewirth** [comment]
@KjelleJ Hmmm I've been unable to reproduce this problem. Perhaps it is a version issue. I've made a few updates to the package since then. Can you confirm you're still experiencing this issue?

**Comment by KjelleJ** [comment]
Updated datto and Anaconda => Problem solved. I guess an old version of
Anaconda could be the problem. 

/Kjell J 

2021-03-22 22:10 skrev Kristie Wi

> @KjelleJ [1] Hmmm I've been unable to reproduce this problem. Perhaps it is a version issue. I've made a few updates to the package since then. Can you confirm you're still experiencing this issue? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1] https://github.com/KjelleJ
[2]
https://github.com/kristiewirth/datto/issues/2#issuecomment-804397491
[3]

**Comment by kristiewirth** [comment]
Glad it's working now!
