### ISSUE TITLE
[FR] Allow users to pass through additional HTML arguments in `FrontEnd.py`

### ISSUE THREAD

**Issue by benhummel** [kristiewirth/datto#4]
### Description of Requested Feature
Allow users to specify `width` and/or `class` in `FrontEnd.dropdown_from_dataframe`

### Context
Currently, width is fixed at 400px for even if this isn't ideal for the webpage. 

Overriding this using CSS can only be done using IDs, which isn't ideal if you're using multiple dropdowns that you want to format the same.

Current workaround is like this:

```
// python: 
d1 = dropdown_from_dataframe("dropdown_a", df, "col_a")
d2 = dropdown_from_dataframe("dropdown_b", df, "col_b") 
[...]
dn = dropdown_from_dataframe("dropdown_n", df, "col_n") 

// CSS:
#dropdown_a, #dropdown_b, [...] #dropdown_n {
    width:  200px;
}
```

Ideal behavior might look something like this:
```
// python:
d1 = dropdown_from_dataframe("dropdown_a", df, "col_a", class="dropdown")
d2 = dropdown_from_dataframe("dropdown_b", df, "col_b", class="dropdown") 
[...]
dn = dropdown_from_dataframe("dropdown_n", df, "col_n", class="dropdown") 

// CSS:
.dropdown {
    width: 200px;
}
```

### Priority
Low pri

**Comment by kristiewirth** [comment]
^^ @benhummel I added some options, let me know if that matches what you were hoping for!

**Comment by benhummel** [comment]
Looks great, thanks @kristiewirth!
